[project]
name = "bettertest"
version = "0.1.0"
description = "Lightweight testing utility for Python functions with profiling and logging."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name = "Sam Lewis", email = "samlewis1999.sl@gmail.com" }
]
dependencies = []

[project.urls]
Homepage = "https://github.com/VarSamLewis/better_test"
Repository = "https://github.com/VarSamLewis/better_test"
