[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bettertest"
version = "0.1.0"
description = "A lightweight Python utility for testing individual functions with profiling and logging."
authors = [
    { name="Your Name", email="your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }