name: Lint and Format

on: 
 pull_request:
  branches:
  - main    

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pipx
        run: python -m pip install pipx

      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff

      - name: Lint code with Ruff
        run: ruff check better_test --output-format=github --target-version=py39

      - name: Check code formatting with Ruff
        run: ruff format better_test --diff --target-version=py39
        continue-on-error: true

      - name: Install build tools
        run: pip install build

      - name: Install package (editable mode)
        run: pip install -e .

      - name: Run unittests
        run: python -m unittest discover